### ISSUE TITLE
Placeholder art assets

### ISSUE THREAD

**Issue by mikepmonson** [mikepmonson/night-on-the-neon-moon#1]
- [x] Placeholder player sprite (8-directional rectangle with arrow on it)
- [x] Placeholder building sprite
- [x] Placeholder enemy sprites
    - [x] Braindead sprite
    - [x] Shooter sprite
- [x] Projectile sprite (color-coded for enemy vs player projectiles)

**Comment by KDiablo** [comment]
Assets finished.
Idea for player model:
Single player sprite, flip in unity for left/right movement, same perspective regardless of up/down movement
