### ISSUE TITLE
Projectile component

### ISSUE THREAD

**Issue by mikepmonson** [mikepmonson/night-on-the-neon-moon#2]
This component will be inherited by a player projectile component and an enemy projectile component.
Required components (this is something you can define with an attribute, so that it is automatically added when the script is added):
 - 2D box (or is it rectangle?) collider
Inspector properties:
 - Velocity (float): the number of units (1f is a full unit) the projectile moves per second.
 - CollidesWith: Tags the collider can hit
Non-serialized properties: (defined by declaring a private variable with no attributes)
 - Trajectory: the angle the projectile moves towards
 - Lifetime (float): The time, in seconds, before this object dissipates. This prevents projectiles from sticking around forever.

Projectiles should, ~~on every Update() (maybe FixedUpdate if we encounter collision detection issues)~~ :
 - ~~Check the next position it will be in for a collidable object using a Raycast2D~~
 - ~~For every object hit by the raycast:~~
 - On `OnCollisionEnter`:
   - Check if object has tags matching CollidesWith
   - If it does not, ~~`continue`~~ 
       - Don't think OnCollisionEnter gives multiple objects per call, think its one collision per call, so `continue` isn't necessary
   - Otherwise, damage it via ReceivesDamage interface methods

**Comment by KDiablo** [comment]
I recommend using the built-in OnCollisionEnter() for checking collisions. we can get the tag of the colliding object and check it against CollidesWith.

**Comment by mikepmonson** [comment]
Made some changes to to the task to reflect that.
We might end up using raycasts later, still, but not the way I described for sure
