### ISSUE TITLE
Enemy component

### ISSUE THREAD

**Issue by mikepmonson** [mikepmonson/night-on-the-neon-moon#6]
This is the class that both our enemy types will inherit from.
Should implement `IDamageable`
Required components:
 - [x] BoxCollider2D
 - [x] Rigidbody2D (prevents enemy stacking)

Public properties:
 - [x] MoveSpeed `float`: The rate at which this enemy will move.
 - [x] CurrentState `EnemyState`: The current state of the enemy.
 - [x] Health `int`: The current health of the enemy.

`CurrentState` enum values:
 - [x] `Entering`: Moving from spawn point into the crater.
 - [x] `Moving`: Moving from spawn point to target.
 - [x] `Attacking`: Braindead-only state that represents the enemy is currently stopped and attacking a building.
 - [x] `Dying`: Represents and enemy that is busy animating its death, which means the player won't take damage from them and they won't move or attack buildings.

As this class is used for nothing other than shared values, it won't be implementing its own methods.

**Comment by KDiablo** [comment]
Remember to set gravity on Rigidbody2D to 0

**Comment by KDiablo** [comment]
Needs a followup issue when creating a prefab, that's where you'd set the rigidbody2d and BoxCollider2D
